### PR TITLE
Improve Driver Code for Our System

### PR DESCRIPTION
**Pull request by yuyuranium**
Hello all, 

Since we successfully booted ibex on the PYNQ, I found several bugs related to the driver. In this PR, I fixed all of them.

1. The generic GPIO read/write function should be able to access either of GPIO/GPIO2, not only GPIO2 (configured as input by default) only while the `read_pin` and `write_pin` functions are convenient wrappers to access a pin assuming GPIO is configured as output and GPIO2 as input already.
2. Write -1 (0xffffffff) to the tri-state control register of GPIO to enable every pin, instead of only the right-most pin.
3. The `uart_getchar()` function has incorrect busy waiting logic.
4. The memory map of UART is updated.

Besides, I added another bare-metal application, echo, to test the functional of reading inputs from UART, which is also able to run on the PYNQ board successfully.

Please let me know if you have comments. Thanks!

### CODE REVIEW

**Comment by waynelinbo** [comment]
In my opinion

1. I think whether it is read / read_pin / write / write_pin / toggle_pin, they all shouldn't preset a gpio as input or output and operate on it
2. The only different between them is at "read/write/toggle a bit" or "read/write a value", I think

So, all of them(functions) need to provides a parameter for the user to specify which GPIO they want to operate on

**Take _gpio_read_pin_ for example :**

```
uint32_t gpio_read_pin(void *gpio, uint32_t pin)
{
    uint32_t data = gpio_read(gpio);
    data = (data >> pin) & 0b1;
    return data;
}
```

If you guys have different ideas, feel free to tell me, thanks.

**Comment by yuyuranium** [comment]
The purpose of the driver design is to provide a simple function to read or write a pin. Since we try to keep our HW as simple as possible, currently we route the GPIO to the LEDs and GPIO2 to buttons directly. For a more generalized design, I think you are correct. We should also be able to configure the mode (I/O) at a pin granularity.

Therefore, I think we could fix to this version for now to have basic I/O function (since we don’t have much time). The improvements of the driver (a more generalized way to configure/set a pin) could be considered as future work.

**Comment by yuyuranium** [comment]
Timer interrupt is tested by using `Barebone-Timer` application. The function looks correct.

**Comment by yuyuranium** [comment]
Congratulations everyone,

We have successfully ported FreeRTOS to our system. The `FreeRTOS-Demo-Hello` application is now running correctly. Let's merge this PR ASAP.

**Review by choucl — APPROVED** [review]

**Pull request merged**
